esphome:
  name: kickstart-rtl8720cf-2mb-992k

rtl87xx:
  board: generic-rtl8720cf-2mb-992k

logger:
web_server:
captive_portal:
mdns:
api:
  encryption:
    key: "xOveavAVYJ6HRBHxlcM71cbEWlSLETaqMEi+oOavDWQ="
ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
